# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/rust/tags/
image: "rust:latest"

.cache:
  variables:
    CARGO_HOME: "${CI_PROJECT_DIR}/cargo_cache"
  before_script:
    - mkdir -p cargo_cache
    - echo $CARGO_HOME
    - apt-get update -qq && apt-get install -y -qq --no-install-recommends build-essential m4 llvm libclang-dev clang
    - git clone --depth=1 https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/zenotta/naom.git ../naom
  cache:
    when: 'on_success'
    key:
      files:
        - Cargo.lock
    paths:
      # Rust cache: All cargo to handle librocksdb-sys
      - cargo_cache
      - target/

# Test and lint the project: do not build binaries
# that require rocksdb and other dependencies
test:cargo:
  extends: '.cache'
  only:
    - merge_requests
  cache:
    key:
      prefix: test2
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo test --workspace --verbose

lint:rustfmt:
  only:
    - merge_requests
  script:
    - rustup component add rustfmt
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo fmt -- --check

lint:clippy:
  extends: '.cache'
  only:
    - merge_requests
  cache:
    key:
      prefix: clippy
  script:
    - rustup component add clippy
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo clippy --all-targets -- -D warnings
