[package]
name = "system"
version = "0.1.0"
authors = ["Byron Houwens <zhion360@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.10"
sha3 = "0.8.2"
rand = "0.7.3"
sodiumoxide = "0.2.5"
rug = "1.7.0"
hex = "0.4.2"
serde = { version = "1.0.104", features = ["derive"] }
bincode = "1.2.1"
futures = "0.3"
tokio = { version = "0.2.13", features = ["full"] }
tokio-util = { version = "0.3", features = ["full"] }
tracing = "0.1.13"
tracing-subscriber = "0.2.3"
tracing-futures = "0.2.3"
bytes = "0.5.4"
clap = "2.33.0"

[features]
mock = []