[package]
name = "system"
version = "0.1.0"
authors = ["Byron Houwens <zhion360@gmail.com>"]
edition = "2018"
readme = "README.md"
description = "The NAOM (Notarised Append Only Memory) crate contains all the code necessary to set up an instance of the Zenotta blockchain."

[dependencies]
chrono = "0.4.10"
config = { version = "0.10.1", features = ["toml"] }
sha3 = "0.9.1"
rand = "0.7.3"
sodiumoxide = "0.2.5"
rug = "1.7.0"
hex = "0.4.2"
serde = { version = "1.0.104", features = ["derive"] }
bincode = "1.2.1"
futures = "0.3"
tokio = { version = "0.2.13", features = ["full"] }
tokio-util = { version = "0.3", features = ["full"] }
tracing = "0.1.13"
tracing-subscriber = "0.2.3"
tracing-futures = "0.2.3"
bytes = { version = "0.5.4", features = ["serde"] }
clap = "2.33.0"
rust-crypto = "0.2.36"
naom = { path = "../naom" }
rocksdb = "0.15.0"
merkletree = "0.21.0"
merkle-log = "0.0.3"
async-std = "1.7.0"
raft = "0.5.0"
protobuf = "~2.0-2.2"
warp = "0.2.5"
serde_json = "1.0.61"

[features]
mock = []
