storage_db_mode = {Test = 0}
miner_db_mode = {Test = 0}
compute_seed_utxo = ["000000", "000001", "000002", "000003"]
compute_raft = 1
storage_raft = 1
compute_partition_full_size = 2
compute_minimum_miner_pool_len = 3

#first node is leader
[[compute_nodes]]
address = "127.0.0.1:12300"

[[compute_nodes]]
address = "127.0.0.1:12301"

[[storage_nodes]]
address = "127.0.0.1:8080"

[[storage_nodes]]
address = "127.0.0.1:8081"

[[miner_nodes]]
address = "127.0.0.1:12340"

[[miner_nodes]]
address = "127.0.0.1:12341"

[[miner_nodes]]
address = "127.0.0.1:12342"

[[miner_nodes]]
address = "127.0.0.1:12343"

[[miner_nodes]]
address = "127.0.0.1:12344"

[[miner_nodes]]
address = "127.0.0.1:12345"

[[user_nodes]]
address = "35.161.167.59:12360"

[[user_nodes]]
address = "127.0.0.1:12361"

[[compute_initial_transactions]]
t_hash = "000000"
receiver_address = "000010"

[[compute_initial_transactions]]
t_hash = "000001"
receiver_address = "000011"
