compute_db_mode = {Live = 0}
storage_db_mode = {Live = 0}
miner_db_mode = {Live = 0}
user_db_mode = {Live = 0}
api_port = 3000
compute_raft = 1
storage_raft = 1
storage_block_timeout = 60000
compute_partition_full_size = 1
compute_minimum_miner_pool_len = 1
jurisdiction = "US"

#first node is leader
[[compute_nodes]]
address = "44.239.251.56:12300"

[[storage_nodes]]
address = "52.40.82.170:8080"

[[miner_nodes]]
address = "52.27.248.13:12340"

[[user_nodes]]
address = "35.155.18.122:12342"
