storage_db_mode = {Test = 0}
miner_db_mode = {Test = 0}
user_db_mode = {Test = 1000}
api_port = 3000
compute_seed_utxo = ["5-000000", "000001", "000010", "2-000011"]
user_wallet_seeds = [["0-000010-123"], ["0-000011-1234", "1-000011-1235"]]
compute_raft = 0
storage_raft = 0
compute_partition_full_size = 1
compute_minimum_miner_pool_len = 1

#first node is leader
[[compute_nodes]]
address = "0.0.0.0:12300"

[[compute_nodes]]
address = "0.0.0.0:12301"

[[storage_nodes]]
address = "0.0.0.0:8080"

[[storage_nodes]]
address = "0.0.0.0:8081"

[[miner_nodes]]
address = "0.0.0.0:12340"

[[miner_nodes]]
address = "0.0.0.0:12341"

[[user_nodes]]
address = "0.0.0.0:12342"

[[user_nodes]]
address = "0.0.0.0:12343"

[[compute_initial_transactions]]
t_hash = "000000"
receiver_address = "000010"

[[compute_initial_transactions]]
t_hash = "000001"
receiver_address = "000011"
