use_live_db = 0
compute_seed_utxo = ["000000", "000001", "000002", "000003"]
compute_raft = 1

#first node is leader
[[compute_nodes]]
address = "127.0.0.1:12300"

[[compute_nodes]]
address = "127.0.0.1:12301"

[[storage_nodes]]
address = "127.0.0.1:8080"

[[storage_nodes]]
address = "127.0.0.1:8081"

[[miner_nodes]]
address = "127.0.0.1:12340"

[[miner_nodes]]
address = "127.0.0.1:12341"

[[user_nodes]]
address = "35.161.167.59:12342"

[[user_nodes]]
address = "127.0.0.1:12343"

[[compute_initial_transactions]]
t_hash = "000000"
receiver_address = "000010"

[[compute_initial_transactions]]
t_hash = "000001"
receiver_address = "000011"
