name: code-scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  scan-code:
    uses:  ${{ vars.ORGANISATION_WORKFLOW_PATH }}/scan-code.yml@main
  # TODO: just here for testing purposes will remove
  scan-image:
    uses: ${{ vars.ORGANISATION_WORKFLOW_PATH }}/scan-image.yml@main
    secrets: inherit
    with:
      IMAGE: ${{ vars.REGISTRY }}/${{ vars.ORGANISATION_NAME }}/node-${{ vars.NODE_TYPE }}:latest