name: code-scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  scan-code:
    uses:  aiblockofficial/workflows/.github/workflows/scan-code.yml@main
  # TODO: just here for testing purposes will remove
  scan-image:
    uses: aiblockofficial/workflows/.github/workflows/scan-image.yml@main
    secrets: inherit
    with:
      IMAGE: ${{ vars.REGISTRY }}/${{ vars.ORGANISATION_NAME }}/node-${{ vars.NODE_TYPE }}:latest