name: build-scan
on: 
  push:
    branches: 
      - main
      - develop

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  build: 
    uses: ${{ vars.ORGANISATION_WORKFLOW_PATH }}/build.yml@main
    with: 
      REGISTRY:  ${{ vars.REGISTRY }}
      REPOSITORY: ${{ vars.REPOSITORY }}
  scan-image:
    uses: ${{ vars.ORGANISATION_WORKFLOW_PATH }}/scan-image.yml@main
    secrets: inherit
    needs: build
    with:
      IMAGE: ${{ vars.REGISTRY }}/aiblockofficial/node-${{ vars.NODE_TYPE }}:${{ github.sha }}