name: build-scan

on:
  push:
    branches: 
      - develop
  pull_request:
    branches:
      - 'develop'

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  matrix: 
    runs-on: ubuntu-latest
    outputs:
      node_types: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: |
          echo "matrix=${{vars.NODE_TYPES}}" >> $GITHUB_OUTPUT
  build:
    needs: matrix
    strategy:
       matrix:
          node: ${{ fromJson(needs.matrix.outputs.node_types) }}
    uses: aiblockofficial/workflows/.github/workflows/node-build.yml@main
    with: 
      REGISTRY:  ${{ vars.REGISTRY }}
      REPOSITORY: ${{ vars.REPOSITORY }}
      NODE_TYPE: ${{ matrix.node }}
  scan-image:
    needs: [ matrix, build ]
    strategy:
      matrix:
        node: ${{ fromJson(needs.matrix.outputs.node_types) }}
    uses: aiblockofficial/workflows/.github/workflows/scan-image.yml@main
    secrets: inherit
    with:
      IMAGE: ${{ vars.REGISTRY }}/${{ vars.ORGANISATION_NAME }}/node-${{ matrix.node }}:${{ github.sha }}
