name: manual-build-and-push

on:
  workflow_dispatch:
    inputs:
      node_type:
        description: "enter a node type (mempool, user, miner, storage)"
        default: "mempool"
        required: true
        type: string
  push:

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  build:
    uses: aiblockofficial/workflows/.github/workflows/build.yml@main
    with:
      REGISTRY: ${{ vars.REGISTRY }}
      REPOSITORY: ${{ vars.REPOSITORY }}
      NODE_TYPE: ${{ inputs.node_type }}