name: build-and-push-miner
on:
#   release:
#     types: [published]
# leaving this in for testing purposes
  push:
    branches: 
      - chore_build-and-push-miner-node-on-release

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  build: 
    uses: aiblockofficial/workflows/.github/workflows/build.yml@main
    with: 
      REGISTRY:  ${{ vars.REGISTRY }}
      REPOSITORY: ${{ vars.REPOSITORY }}
      NODE_TYPE: 'miner'