name: build-and-push-miner

on:
  push:
    tags: ["v*.*.*"]

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  
      - name: Set Version
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
  
      - uses: aiblockofficial/workflows/.github/workflows/node-build.yml@main
        with:
          REGISTRY: ${{ vars.REGISTRY }}
          REPOSITORY: ${{ vars.REPOSITORY }}
          VERSION: ${{ steps.vars.outputs.tag }}
          NODE_TYPE: "miner"
