name: build-and-push-miner
on:
  release:
    types: [published]

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  build: 
    uses: ${{ vars.ORGANISATION_WORKFLOW_PATH }}/build.yml@main
    with: 
      REGISTRY:  ${{ vars.REGISTRY }}
      REPOSITORY: ${{ vars.REPOSITORY }}
      NODE_TYPE: 'miner'