name: Slack notification

on:
  workflow_call:
    inputs:
      heading:
        required: true
        type: string
      info:
        required: true
        type: string
      url:
        required: true
        type: string
    secrets:
      webhook:
        required: true

jobs:
  slack-notify:
    runs-on: ubuntu-latest
    steps:
      - uses: slackapi/slack-github-action@v1.25.0
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
            "blocks": [
                {
                "type": "header",
                "text": {
                    "type": "plain_text",
                    "text": "${{ inputs.heading }} (${{ vars.REPOSITORY }})",
                    "emoji": true
                }
                },
                {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": "${{ inputs.info }}"
                },
                "accessory": {
                    "type": "button",
                    "text": {
                    "type": "plain_text",
                    "text": "View Results",
                    "emoji": true
                    },
                    "value": "click_me_123",
                    "url": "${{ inputs.url }}",
                    "action_id": "button-action"
                }
                }
            ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.webhook }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
