name: Slack notification

on:
  workflow_call:
    inputs:
      heading:
        required: true
        type: string
    secrets:
        webhook:
            required: true

jobs:
  slack-notify:
    runs-on: ubuntu-latest
    steps:
    - uses: slackapi/slack-github-action@v1.25.0
      with:
        # For posting a rich message using Block Kit
        payload: |
            {
            "blocks": [
                {
                "type": "header",
                "text": {
                    "type": "plain_text",
                    "text": ${{ inputs.heading }},
                    "emoji": true
                }
                },
                {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": "Repository: *${{ vars.REPOSITORY }}* with Status: *${{ job.status }}* for PR *${{ github.event.pull_request.title }}*"
                },
                "accessory": {
                    "type": "button",
                    "text": {
                    "type": "plain_text",
                    "text": "View Results",
                    "emoji": true
                    },
                    "value": "click_me_123",
                    "url": "${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
                    "action_id": "button-action"
                }
                }
            ]
            }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.webhook }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
