name: Run integration tests

on:
  pull_request:
    branches: ["*"]

jobs:
  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        id: toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Clippy check
        timeout-minutes: 30
        run: cargo clippy --all-targets --all-features -- -Dwarnings

      - name: Run integration tests
        timeout-minutes: 30
        run: cargo test --release -- --test-threads=1

      - name: Send custom JSON data to Slack workflow
        id: slack_success
        uses: ./.github/workflows/slack-msg.yml 
        if: success()
        with:
          heading: "Tests Passed :large_green_circle:"

      - name: Send custom JSON data to Slack workflow
        id: slack_fail
        uses: ./.github/workflows/slack-msg.yml
        if: failure()
        with:
          heading: "Tests Failed :red_circle:"