name: Run integration tests

on:
  pull_request:
    branches: ["*"]

jobs:
  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        id: toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Clippy check
        timeout-minutes: 30
        run: cargo clippy --all-targets --all-features -- -Dwarnings

      - name: Run integration tests
        timeout-minutes: 30
        run: cargo test --release -- --test-threads=1

      - name: Send custom JSON data to Slack workflow
        id: slack_success
        uses: slackapi/slack-github-action@v1.25.0
        if: success()
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "Tests Passed :mechanical_arm:",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Status: ${{ job.status }}"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "View Results",
                      "emoji": true
                    },
                    "value": "click_me_123",
                    "url": "${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
                    "action_id": "button-action"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

      - name: Send custom JSON data to Slack workflow
        id: slack_fail
        uses: slackapi/slack-github-action@v1.25.0
        if: failure()
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "Tests Failed :skull_and_crossbones:",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Status: ${{ job.status }}"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "View Results",
                      "emoji": true
                    },
                    "value": "click_me_123",
                    "url": "${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
                    "action_id": "button-action"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK